DIST_SOURCE_DIR = $(DIST_DIR)/$(BMN_SHORT_NAME)
DIST_TARGET = $(DIST_DIR)/$(BMN_SHORT_NAME)-$(BMN_VERSION_STRING)-$(BMN_PLATFORM_STRING).AppImage

APPIMAGE_ICON = $(DIST_SOURCE_DIR)/$(BMN_SHORT_NAME)$(suffix $(BMN_ICON_LINUX_FILE_PATH))
APPIMAGE_DESKTOP = $(DIST_SOURCE_DIR)/$(BMN_SHORT_NAME).desktop
APPIMAGE_APPRUN = $(DIST_SOURCE_DIR)/AppRun

$(APPIMAGE_ICON): $(BMN_ICON_LINUX_FILE_PATH)
	$(call CP,$<,$@)

$(APPIMAGE_DESKTOP): $(CONTRIB_PLATFORM_DIR)/application.desktop
	$(call ENVSUBST_FILE,$<,$@)

$(APPIMAGE_APPRUN): $(CONTRIB_PLATFORM_DIR)/AppRun.sh
	$(call ENVSUBST_FILE,$<,$@)
	$(call CHMOD_EXEC,$@)

dist:: \
		$(APPIMAGE_ICON) \
		$(APPIMAGE_DESKTOP) \
		$(APPIMAGE_APPRUN)
	ARCH=X86_64 $(APPIMAGETOOL) \
		--no-appstream \
		--verbose \
		--comp gzip \
		$(DIST_SOURCE_DIR) \
		$(DIST_TARGET)

dist-clean::
	$(call RM,$(APPIMAGE_ICON))
	$(call RM,$(APPIMAGE_DESKTOP))
	$(call RM,$(APPIMAGE_APPRUN))
