[build-system]
requires = ["setuptools >= 42.0.0", "wheel >= 0.36"]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ["py310"]
line-length = 79

[tool.isort]
profile = "black"
py_version = 310
line_length = 79
